### ISSUE TITLE
Literature and Data curation

### ISSUE THREAD

**Issue by eli-cipriano** [eli-cipriano/BioRefine#6]
# LitReview
We want to get as much data as possible for this program to really shine. As long as we keep the CSV lists organized, we should be able to make it as complex as we want.

**This is the link to our google sheet:**
https://docs.google.com/spreadsheets/d/113IRwphAABcc4IHipYvIeVwfUYU0Zu-tDk7q0-pS9Ts/edit?usp=sharing

**Comment by Hdedstrom** [comment]
The csv here[https://github.com/eli-cipriano/BioRefine/blob/data/data_sub2prod.csv](url) adds more data to the sheet. I left your data untouched at the top of the file; I'm not sure where you got it from so didn't update sources. 

There's also a bibliography in a txt file, which may not be the best format but it works

I'll keep adding to this csv as I continue consulting literature!

**Comment by eli-cipriano** [comment]
So helpful! Thanks. I invented most of the data just to test the code, so
we can delete it once we have some real data. I may not be available at
11:15 tomorrow but i’ll let you know.

Best,
Eli
